name: g-docker
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - flask
      - pandas
      - pm4py
      - pcst_fast
      - torch-geometric
      - langchain
      - langchain_community
      - transformers
      - gensim
      - scipy==1.10.1
      - accelerate
      - openai
